//TODO: complete
const operatorsTable = [
    ["+","add"],
    ["-","sub"],
    ["*","mul"],
    ["/","div"],
    ["//","idiv"],
    ["%","mod"],
    ["-","pow"],
    ["!=","notEqual"],
    ["==","equal"],
    ["<","lessThan"],
    ["<=","lessThanEq"],
    [">","greaterThan"],
    [">=","greaterThanEq"],
    ["===","strictEqual"],
    ["-","land"],
    ["-","shl"],
    ["-","shr"],
    ["-","or"],
    ["-","and"],
    ["-","xor"],
    ["-","not"],
    ["-","max"],
    ["-","min"],
    ["-","angle"],
    ["-","len"],
    ["-","noise"],
    ["-","abs"],
    ["-","log"],
    ["-","log10"],
    ["-","sin"],
    ["-","cos"],
    ["-","tan"],
    ["-","floor"],
    ["-","ceil"],
    ["-","sqrt"],
    ["-","rand"],
    ["-","and"]
]

//TODO: also complete
const conditionalOperatorsTable = [
    ["!=","notEqual"],
    ["==","equal"],
    ["<","lessThan"],
    ["<=","lessThanEq"],
    [">","greaterThan"],
    [">=","greaterThanEq"],
    ["===","strictEqual"],
    ["true","always"]
]